# Install: uv add pre-commit && pre-commit install
repos:
  # Validate maintainer Markdown files.
  - repo: local
    hooks:
      - id: validate-maintainers
        name: Validate maintainer Markdown files
        entry: yarn validate:maintainers
        language: system
        stages: [pre-commit]
        files: ^content/maintainers/.*\.md$
        pass_filenames: false

  # cspell
 # - repo: https://github.com/streetsidesoftware/cspell-cli
 #   rev: v9.4.0
 #   hooks:
 #     - id: cspell
 #       name: Spell check markdown files
 #       types: [text]
 #       args:
 #         - --config
 #         - cspell.json
 #         - --no-must-find-files
 #     - id: cspell
 #       name: check commit message spelling
 #       args:
 #         - --config
 #         - cspell.json
 #         - --no-must-find-files
 #         - --no-progress
 #         - --no-summary
 #         - --files
 #         - .git/COMMIT_EDITMSG
 #       stages: [commit-msg]
 #       always_run: true

