name: cspell - Spell Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CSpell
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: "./cspell.json"
          incremental_files_only: false

      - name: Show message on CSpell failure
        if: failure() # This conditional makes the step run only on failure
        run: |
          echo "❌ Spell check failed."
          echo "Is it a false error? Custom words can be added to ./.cspell/maintainer-words.txt"
